config/routes.rb
WisatoNagari::Application.routes.draw do
    
  resources :tempats

  resources :makanans

  resources :budayas

  resources :daerahs

  resources :admins
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete

  get "wisata/index"
  match 'kemakan', to: 'wisata#makanan'
  match 'kedaerah', to: 'wisata#daerah'
  match 'kebudayaan', to: 'wisata#kebudayaan'

  resources :kontens
  
  

  root :to => 'wisata#index'

end

app/models/daerah.rb
class Daerah < ActiveRecord::Base
  attr_accessible :deskripsidaerah, :namadaerah, :photo
  has_attached_file :photo, styles: { big:"300x300", small: "150x150>", thumb: "25x25>" }
  validates :photo, presence: true
  has_many :budaya
  has_many :makanan
  has_many :konten
end

app/controllers/daerahs_controller.rb
class DaerahsController < ApplicationController
  # GET /daerahs
  # GET /daerahs.json
  def index
    @daerahs = Daerah.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @daerahs }
    end
  end

  # GET /daerahs/1
  # GET /daerahs/1.json
  def show
    @daerah = Daerah.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @daerah }
    end
  end

  # GET /daerahs/new
  # GET /daerahs/new.json
  def new
    @daerah = Daerah.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @daerah }
    end
  end

  # GET /daerahs/1/edit
  def edit
    @daerah = Daerah.find(params[:id])
  end

  # POST /daerahs
  # POST /daerahs.json
  def create
    @daerah = Daerah.new(params[:daerah])

    respond_to do |format|
      if @daerah.save
        format.html { redirect_to @daerah, notice: 'Daerah was successfully created.' }
        format.json { render json: @daerah, status: :created, location: @daerah }
      else
        format.html { render action: "new" }
        format.json { render json: @daerah.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /daerahs/1
  # PUT /daerahs/1.json
  def update
    @daerah = Daerah.find(params[:id])

    respond_to do |format|
      if @daerah.update_attributes(params[:daerah])
        format.html { redirect_to @daerah, notice: 'Daerah was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @daerah.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daerahs/1
  # DELETE /daerahs/1.json
  def destroy
    @daerah = Daerah.find(params[:id])
    @daerah.destroy

    respond_to do |format|
      format.html { redirect_to daerahs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/daerahs_helper.rb
module DaerahsHelper
end

app/views/daerahs/_form.html.erb
<%= form_for(@daerah) do |f| %>
  <% if @daerah.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@daerah.errors.count, "error") %> prohibited this daerah from being saved:</h2>

      <ul>
      <% @daerah.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :namadaerah %><br />
    <%= f.text_field :namadaerah %>
  </div>
  <div class="field">
    <%= f.label :deskripsidaerah %><br />
    <%= f.text_area :deskripsidaerah %>
  </div>
   <div class="field">
  	<%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/daerahs/edit.html.erb
<h1>Editing daerah</h1>

<%= render 'form' %>

<%= link_to 'Show', @daerah %> |
<%= link_to 'Back', daerahs_path %>

app/views/daerahs/index.html.erb
<h1>Listing daerahs</h1>

<table>
  <tr>
    <th>Namadaerah</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @daerahs.each do |daerah| %>
  <tr>
    <td><%= daerah.namadaerah %></td>
    <td><%= link_to 'Show', daerah %></td>
    <td><%= link_to 'Edit', edit_daerah_path(daerah) %></td>
    <td><%= link_to 'Destroy', daerah, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Daerah', new_daerah_path %>

app/views/daerahs/new.html.erb
<h1>New daerah</h1>

<%= render 'form' %>

<%= link_to 'Back', daerahs_path %>

app/views/daerahs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Namadaerah:</b>
  <%= @daerah.namadaerah %>
</p>

<p>
  <b>Deskripsidaerah:</b>
  <%= @daerah.deskripsidaerah %>
</p>
<%= image_tag @daerah.photo.url(:big) %>

<%= link_to 'Edit', edit_daerah_path(@daerah) %> |
<%= link_to 'Back', daerahs_path %>