config/routes.rb
WisatoNagari::Application.routes.draw do
    
  resources :tempats

  resources :makanans

  resources :budayas

  resources :daerahs

  resources :admins
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete

  get "wisata/index"
  match 'kemakan', to: 'wisata#makanan'
  match 'kedaerah', to: 'wisata#daerah'
  match 'kebudayaan', to: 'wisata#kebudayaan'

  resources :kontens
  
  

  root :to => 'wisata#index'

end

app/views/admins/_form.html.erb
<% if signed_in?%>
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="field">
    <%= f.label :nama %><br />
    <%= f.text_field :nama %>
  </div>
  <div class="field">
    <%= f.label :email %><bhttp://localhost:3000/adminsr />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    password<br/>
	<%= f.password_field :password%>
  </div>
  <div class="field">
    konfirmasi password<br/>
	<%= f.password_field :password_confirmation%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%end%>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Listing admins</h1>

<table>
  <tr>
    <th>Nama</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admins.each do |admin| %>
  <tr>
    <td><%= admin.nama %></td>
    <td><%= admin.password_digest %></td>
    <td><%= link_to 'Show', admin %></td>
    <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
    <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nama:</b>
  <%= @admin.nama %>
</p>

<p>
  <b>Password digest:</b>
  <%= @admin.password_digest %>
</p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>