config/routes.rb
WisatoNagari::Application.routes.draw do
    
  resources :tempats

  resources :makanans

  resources :budayas

  resources :daerahs

  resources :admins
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete

  get "wisata/index"
  match 'kemakan', to: 'wisata#makanan'
  match 'kedaerah', to: 'wisata#daerah'
  match 'kebudayaan', to: 'wisata#kebudayaan'

  resources :kontens
  
  

  root :to => 'wisata#index'

end

app/models/konten.rb
class Konten < ActiveRecord::Base
  belongs_to :daerah
  attr_accessible :deskripsi, :namawisata, :tempat, :photo, :daerah_id, :photo
  has_attached_file :photo, styles: { big:"300x300", small: "150x150>", thumb: "25x25>" }
  validates :photo, presence: true
  validates :deskripsi, :namawisata, :tempat, presence: true
end

app/controllers/kontens_controller.rb
class KontensController < ApplicationController
  # GET /kontens
  # GET /kontens.json
  def index
    @kontens = Konten.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kontens }
    end
  end

  # GET /kontens/1
  # GET /kontens/1.json
  def show
    @konten = Konten.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @konten }
    end
  end

  # GET /kontens/new
  # GET /kontens/new.json
  def new
    @konten = Konten.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @konten }
    end
  end

  # GET /kontens/1/edit
  def edit
    @konten = Konten.find(params[:id])
  end

  # POST /kontens
  # POST /kontens.json
  def create
    @konten = Konten.new(params[:konten])

    respond_to do |format|
      if @konten.save
        format.html { redirect_to @konten, notice: 'Konten was successfully created.' }
        format.json { render json: @konten, status: :created, location: @konten }
      else
        format.html { render action: "new" }
        format.json { render json: @konten.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kontens/1
  # PUT /kontens/1.json
  def update
    @konten = Konten.find(params[:id])

    respond_to do |format|
      if @konten.update_attributes(params[:konten])
        format.html { redirect_to @konten, notice: 'Konten was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @konten.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kontens/1
  # DELETE /kontens/1.json
  def destroy
    @konten = Konten.find(params[:id])
    @konten.destroy

    respond_to do |format|
      format.html { redirect_to kontens_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/kontens_helper.rb
module KontensHelper
end

app/views/kontens/_form.html.erb
<%= form_for @konten, :html => { :multipart => true } do |f| %>
  <% if @konten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@konten.errors.count, "error") %> prohibited this konten from being saved:</h2>

      <ul>
      <% @konten.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  <div class="field">
    <%= f.label :namawisata %><br />
    <%= f.text_field :namawisata %>
  </div>
  <div class="field">
    <%= f.label :tempat %><br />
    <%= f.text_field :tempat %>
  </div>
  <div class="field">
  	<%=f.label "provinsi"%>
  <%= f.select :daerah_id , options %>
  </div>
  <div class="field">
    <%= f.label :deskripsi %><br />
    <%= f.text_area :deskripsi %>
  </div>
  <div class="field">
  	<%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kontens/edit.html.erb
<h1>Editing konten</h1>

<%= render 'form' %>

<%= link_to 'Show', @konten %> |
<%= link_to 'Back', kontens_path %>

app/views/kontens/index.html.erb
<h1>Listing kontens</h1>

<table>
  <tr>
  	<th></th>
    <th>Namawisata</th>
    <th>Tempat</th>
    <th>Provinsi</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kontens.each do |konten| %>
  <tr>
  	<td><%= image_tag konten.photo(:thumb)%></td>
    <td><%= konten.namawisata %></td>
    <td><%= konten.tempat %></td>
    <td><%= konten.daerah.namadaerah%> </td>
    <td><%= link_to 'Show', konten %></td>
    <td><%= link_to 'Edit', edit_konten_path(konten) %></td>
    <td><%= link_to 'Destroy', konten, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Konten', new_konten_path %>

app/views/kontens/new.html.erb
<h1>New konten</h1>

<%= render 'form' %>

<%= link_to 'Back', kontens_path %>

app/views/kontens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Namawisata:</b>
  <%= @konten.namawisata %>
</p>

<p>
  <b>Tempat:</b>
  <%= @konten.tempat %>
</p>

<p>
  <b>Deskripsi:</b>
  <%= @konten.deskripsi %>
</p>
<p>
  
  <%= image_tag @konten.photo.url(:big) %>
</p>

<%= link_to 'Edit', edit_konten_path(@konten) %> |
<%= link_to 'Back', kontens_path %>