config/routes.rb
WisatoNagari::Application.routes.draw do
    
  resources :tempats

  resources :makanans

  resources :budayas

  resources :daerahs

  resources :admins
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete

  get "wisata/index"
  match 'kemakan', to: 'wisata#makanan'
  match 'kedaerah', to: 'wisata#daerah'
  match 'kebudayaan', to: 'wisata#kebudayaan'

  resources :kontens
  
  

  root :to => 'wisata#index'

end

app/models/budaya.rb
class Budaya < ActiveRecord::Base
  has_attached_file :photo, styles: { big:"300x300", small: "150x150>", thumb: "25x25>" }
  validates :photo, presence: true
  attr_accessible :deskripsibudaya, :namabudaya, :daerah_id, :photo
  belongs_to :daerah
end

app/controllers/budayas_controller.rb
class BudayasController < ApplicationController
  # GET /budayas
  # GET /budayas.json
  
  def index
    @budayas = Budaya.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @budayas }
    end
  end

  # GET /budayas/1
  # GET /budayas/1.json
  def show
    @budaya = Budaya.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @budaya }
    end
  end

  # GET /budayas/new
  # GET /budayas/new.json
  def new
    
    @budaya = Budaya.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @budaya }
    end
  end

  # GET /budayas/1/edit
  def edit
    @budaya = Budaya.find(params[:id])
  end

  # POST /budayas
  # POST /budayas.json
  def create
    @budaya = Budaya.new(params[:budaya])
    
    respond_to do |format|
      if @budaya.save
        format.html { redirect_to @budaya, notice: 'Budaya was successfully created.' }
        format.json { render json: @budaya, status: :created, location: @budaya }
      else
        format.html { render action: "new" }
        format.json { render json: @budaya.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /budayas/1
  # PUT /budayas/1.json
  def update
    @budaya = Budaya.find(params[:id])

    respond_to do |format|
      if @budaya.update_attributes(params[:budaya])
        format.html { redirect_to @budaya, notice: 'Budaya was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @budaya.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budayas/1
  # DELETE /budayas/1.json
  def destroy
    @budaya = Budaya.find(params[:id])
    @budaya.destroy

    respond_to do |format|
      format.html { redirect_to budayas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/budayas_helper.rb
module BudayasHelper
end

app/views/budayas/_form.html.erb
<%= form_for(@budaya) do |f| %>
  <% if @budaya.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@budaya.errors.count, "error") %> prohibited this budaya from being saved:</h2>

      <ul>
      <% @budaya.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :namabudaya %><br />
    <%= f.text_field :namabudaya %>
  </div>
   <div class="field">
  	<%=f.label "provinsi"%>
  <%= f.select :daerah_id , options %>
  </div>
  <div class="field">
    <%= f.label :deskripsibudaya %><br />
    <%= f.text_area :deskripsibudaya %>
  </div>
   <div class="field">
  	<%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/budayas/edit.html.erb
<h1>Editing budaya</h1>

<%= render 'form' %>

<%= link_to 'Show', @budaya %> |
<%= link_to 'Back', budayas_path %>

app/views/budayas/index.html.erb
<h1>Listing budayas</h1>

<table>
  <tr>
    <th>Nama budaya</th>
    <th>Asal</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @budayas.each do |budaya| %>
  <tr>
    <td><%= budaya.namabudaya %></td>
    <td><%= budaya.daerah.namadaerah %></td>
    <td><%= link_to 'Show', budaya %></td>
    <td><%= link_to 'Edit', edit_budaya_path(budaya) %></td>
    <td><%= link_to 'Destroy', budaya, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Budaya', new_budaya_path %>

app/views/budayas/new.html.erb
<h1>New budaya</h1>
<%= render 'form' %>
<%= link_to 'Back', budayas_path %>

app/views/budayas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Namabudaya:</b>
  <%= @budaya.namabudaya %>
</p>

<p>
  <b>Deskripsibudaya:</b>
  <%= @budaya.deskripsibudaya %>
</p>
<%= image_tag @budaya.photo.url(:big) %>

<%= link_to 'Edit', edit_budaya_path(@budaya) %> |
<%= link_to 'Back', budayas_path %>